### ISSUE TITLE
[Kubernetes] unable to mount if not root user

### ISSUE THREAD

**Issue by mauliksoneji** [GoogleCloudPlatform/gcsfuse#396]
I am running gcsfuse in postStart lifecycle hook to mount a GCS bucket on the pod.
My pod is running with a non-root user with uid 1000.

Here is my deployment config:
```
        lifecycle:
          postStart:
            exec:
              command:
              - gcsfuse --key-file /home/.secrets/auth.json -o ro --implicit-dirs
                --uid 1000 --gid 1000 <bucket> /home/myprocess
          preStop:
            exec:
              command:
              - fusermount -u /home/myprocess
```

I have tried running without providing `uid` and `gid` and getting the same results.
I have also tried changing the user by executing `su root` and then executing the command, still the gcsfuse command fails with the same log provided below.

The postStart hook fails with the following log:
```
Exec lifecycle hook ([gcsfuse --key-file /home/.secrets/auth.json -o ro --implicit-dirs --uid 1000 --gid 1000 <bucket-name> /home/myprocess]) for Container "container-0" in Pod "pod-0-6d4b7547b4-6gtn6_temp3(5bc2a7e0-a71c-11ea-81f2-42010afffdc8)" failed - error: command 'gcsfuse --key-file /home/.secrets/auth.json -o ro --implicit-dirs --uid 1000 --gid 1000 <bucket-name> /home/myprocess' exited with 126: , message: "OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused \"exec: \\\"gcsfuse --key-file /home/.secrets/auth.json -o ro --implicit-dirs --uid 1000 --gid 1000 <bucket-name> /home/myprocess\\\": stat gcsfuse --key-file /home/.secrets/auth.json -o ro --implicit-dirs --uid 1000 --gid 1000 <bucket-name> /home/myprocess: no such file or directory\": unknown\r\n"
```

Can you please help me with command level changes so that I can run gcsfuse from non root user?
Thanks

**Comment by lezh** [comment]
The recommended way of using gcsfuse is to run it in a csi driver. 

For instance, [this one](https://github.com/ofek/csi-gcs/) uses gcsfuse [here](https://github.com/ofek/csi-gcs/blob/master/pkg/driver/node.go#L105).

**Comment by yogeshbidari** [comment]
Can you try using below code:

```
        lifecycle:
          postStart:
            exec:
              command: ["gcsfuse", "--key-file", "/home/.secrets/auth.json", "-o", "ro", "--implicit-dirs", "--uid", "1000", "--gid", "1000", "<bucket>", "/home/myprocess"]
          preStop:
            exec:
              command: ["fusermount", "-u", "/home/myprocess"]
```
